apiVersion: v2
name: prometheus
version: 1.0.0

dependencies:
  - name: prometheus-operator-crds
    version: 13.0.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 61.4.0
    repository: https://prometheus-community.github.io/helm-charts
