apiVersion: v1
kind: ConfigMap
metadata:
  name: entities-configuration
  labels:
    home-assistant-config: "1"
  annotations:
    io.home-assistant/config-folder: "/config/entities"
data:
{{ (.Files.Glob "configuration/entities/**.yaml").AsConfig | indent 2 }}
