kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "immich.fullname" . }}-machine-learning
  labels:
    app.kubernetes.io/name: {{ template "immich.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "immich-machine-learning"
    {{- include "labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.server.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "immich.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "immich-machine-learning"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "immich.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "immich-machine-learning"
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.machineLearning.image.registry }}/{{ .Values.machineLearning.image.repository }}:{{ .Values.machineLearning.image.tag }}"
          imagePullPolicy: {{ .Values.machineLearning.image.pullPolicy }}
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.clusterName }}-app
                  key: host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.clusterName }}-app
                  key: username
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.clusterName }}-app
                  key: dbname
            - name: REDIS_HOSTNAME
              value: {{ .Release.Name }}-redis-master
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://{{ template "immich.fullname" . }}-machine-learning:3003
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.clusterName }}-app
                  key: password
          livenessProbe:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              port: http
              path: /ping
          readinessProbe:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              port: http
              path: /ping
          volumeMounts:
            - name: cache
              mountPath: /cache
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          resources: {{ toYaml .Values.machineLearning.resources | nindent 12 }}
      volumes:
        - name: cache
          emptyDir: {}
