apiVersion: v2
name: grafana
version: 1.0.156

dependencies:
  - name: grafana
    version: 10.5.10
    repository: https://grafana.github.io/helm-charts
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
