{{- range $endpoint := .Values.ingress }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $endpoint.name }}
spec:
  type: ExternalName
  externalName: '{{ $endpoint.name }}.{{ $endpoint.zone }}.mobrockers.com'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $endpoint.name }}
  {{- if $endpoint.auth }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
        'https://{{ $endpoint.name }}.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri'
    nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
  {{- end }}
spec:
  rules:
  - host: '{{ $endpoint.name }}.mobrockers.com'
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ $endpoint.name }}
            port:
              name: http
        pathType: Prefix
  tls:
  - hosts:
    - '{{ $endpoint.name }}.mobrockers.com'
{{- if $endpoint.auth }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ $endpoint.name }}-auth'
spec:
  rules:
  - host: '{{ $endpoint.name }}.mobrockers.com'
    http:
      paths: 
      - path: /outpost.goauthentik.io
        pathType: Prefix
        backend:
          service:
            name: ak-outpost-authentik-embedded-outpost
            port:
              number: 9000
  tls:
  - hosts:
    - '{{ $endpoint.name }}.mobrockers.com'
{{- end }}
{{- end }}
