
providers:
  core:
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.10.1
  ipam:
    image:
      repository: registry.k8s.io/capi-ipam-ic/cluster-api-ipam-in-cluster-controller
      tag: v1.0.1
  infrastructure:
    proxmox:
      image:
        repository: ghcr.io/ionos-cloud/cluster-api-provider-proxmox
        tag: v0.7.0
  bootstrap:
    talos:
      image:
        repository: ghcr.io/siderolabs/cluster-api-talos-controller
        tag: v0.6.9
  controlPlane:
    talos:
      image:
        repository: ghcr.io/siderolabs/cluster-api-control-plane-talos-controller
        tag: v0.5.8
