apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/_base
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../cluster/cluster.yaml
      - ../connectivity/connectivity.yaml
      - ../devices/devices.yaml
      - ../home/home.yaml
      - ../media/media.yaml
      - ../monitoring/monitoring.yaml
      - ../storage/storage.yaml
      - ../test/test.yaml
  syncPolicy:
    syncOptions:
     - FailOnSharedResource=true
  destination:
    name: in-cluster
    namespace: argocd
