ingress-nginx:
  revisionHistoryLimit: 0

  controller:
    kind: DaemonSet

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    
    service:
      enabled: true
      external:
        enabled: false 
      internal:
        enabled: true
        annotations: 
          'io.cilium/lb-ipam-ips': 10.0.10.130
        externalTrafficPolicy: Local

    allowSnippetAnnotations: true
    ingressClassResource:
      default: true
    
    extraArgs:
      default-ssl-certificate: ingress-nginx/default-wildcard-certificate
      update-status-on-shutdown: 'false'
    config:
      enable-ocsp: 'true'
      strict-validate-path-type: 'false'
