apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-bgp-peer-config
spec:
  timers:
    connectRetryTimeSeconds: 30
    holdTimeSeconds: 15
    keepAliveTimeSeconds: 5
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 30
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: loadbalancers
