---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: prometheus
spec:
  encryptedData:
    alertmanager.yaml: AgBR3ivVPNNis3mJ69qoh7VfeY9U66D8FAr4ErVZ1Qqd7J0lPt37NHz6rIdMw/sGFmgTXp6Ri6h6j7Eokeq+5+8kojJjSQjFInQyGRf5sc5yAD+ZW5nTvjMsxksJE/pYjmk2ssisp8V+fBL3Acy68eJvi2eKsmFtLGNIJCMqbcHVtZL1bu/31PPQd9+zu0lNGMB/JDVrGr9hE2wIFeVW6T4iH1D6P5iD0oTjjh6lwX65sksqKTHtAFI5gXxBWtOGtxk/ej6l9747g9qYrLQ8Mhyxqh485RuihYxffOEYIGUXhrTo+QLdhIZ0TRFQut2HXCNl65k7i9jP2rOVSMOQCbdxtaMbYFDIJRdNvL+VOvrgpfKONp/o2klSvEOjCz1pH/iUW8tMcD+OLZkHHdQcXGLPbu3oa62twficgCZvrYOwomFLDASvZjsIbuLwvlBdQdQ8BkzSAEssbcSk1RiyuTXV6+YHKCtF/Ig3CJkYOJIUysFo3ZH/TCwA67THux0N9J43oCRpPwoaRKvHShT/umyvREU+s8t6ohvYLjQHb4howM2/uGwvP6RzsFDgD8yz9cPCYLCu86ENaIdZfC8I4lkoyVWZa9xV1LSKXFw8k2PDBzEQUcxktKBh0b4/hiJZBBt9CxMs+V9GtcsaoUaTJmwKevdfA9NEZUkx3KgqBm8BXNhj/K1nkAWwD9endOaceB6H07DTTwEpN2XkCZhZWyneVkRSo4VW+lRleMbNbxGG+qTCY35Erk99fLPTfJ+5+4EqjSlJeJJYy6XtYiIsHJj8XeBC7Hm2HQ2h+5g0jL25zDV0QVSQXF2LBezSAYZgLnv3unsA5B6g1/PV3tINfpE4Ty5/E9X6k2FE9Ik9KynlNKlgGRoPkVQPwOkqz3sBPkGXs6alqpSn+LWVREg7CrhhiTCEF6UdZgfQaxung9JeVtkT9mQhfld0gUBBUbuQKC+lorEINlGZ/5zKj3znOcgMGTSa/XH9qy/xOjILlCaOl5Y1Ad4oqiHuUvEt8mYWLyG92mwvruUOOxGHtJidbUlwY3JqgGVY2lyLiGmdYOT4LYtF5L2c44PWTE5UyieJcCR/NNPOmZjhn3Mojqrwps5W2oYnBo7/9+mBhtyZuan22sWjEe+Q+lPd0Ombgx8GYw+ZNKI2gj0aBgHeJZVNrHl+knhyaB18+peoaiV8FvLrUbaFn/ZSorkdjW0Y5fNSiwUJXYKwi7IkULE4l9VBPebVNq0nTUQsB9kMzt37AqhXGGuKTopqdGD+iGFOQGhwl6GD/SuSDE1NVnTxjirk37DkyCuw8GlYQEAtiMfLj+/HixhbjbbNuHOw0XqEm2Kfnt04huMXNuSV5kcI6fIU6QidHK0=
  template:
    metadata:
      name: alertmanager-config
      namespace: prometheus
