---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-oidc-secret
  namespace: prometheus
spec:
  encryptedData:
    client-secret: AgC2NEtJ/8joVQUmjXOrqrXYe4U0Tl6aDXJTjmdIC0hGg5fOhe/5ihU234VLoV2kJAYE1RhIIyYSy9V644O58qAtD6KK49GkCwOze4JV0vQSb3y056ok+LwAEnfgLXuOd1eYLBc1EAAKesy6iH9oht2N8+XExciM07XA/os8FOgsLF6G20y1Etyw7hJaIX2gnQG+wV7qBhHp6M1srawpLVpPDcdWUlzokGdupzWlUX+vlAOH0LSZln4o3SIvv9e+jTG00T5heimGCW7iYlC2t+kh+LWD8RBiodf82a0zJGCDhtz1ZLH+CxyA8tXql/fCxhIY8KgC76rX1vlAG3CR4vT4FEeTc4wZXUwAbwR2+m4VqnlhXs6tWtrRDh9VQRDB5/yvyCXA/2HI0PviGleUEdQ6JIFYdVImYJNUuQjVrU4HfpG5WRb1y88dbGkIenE7SXpVYupN3yiLp4pNGSqyjAGIFzrFhx/5H0L5nHdyY6hl1b4P4+MHArBGEASu/2bVHLDamg5JML2s7shjpR7ROhhvPvYR7obLJ/6NLFVSLs/7GHMTc6nThjIKZgpiq1/OXNs6G1HjUuHjSTi1D5YFPTqEYJzJ3xDpqN9obW5Kz4Y9B55ukO+bUEVUnbSvvvNyAW+bycHPFvpAGkQmkMakteKzF3jieq8bSqhvoM9g2zAtB+F44i6F/eotUrJAp8X+vJfu0ZqITkRb50DQ9WembzI6wU+/tDCrTuXOXUyhu0OuUfV3I0xHB1tIxBc3omPMexSOw6d40NVz5opF5UJ03foSKGU/Z3zaT7uI8zycWrImU43auJ2M4TvTAFzw6Rb2ngTA7LKCSfjr9G5PTKeNyOxP5HuJeXvCIjcblpV6IKn9eQ==
  template:
    metadata:
      name: alertmanager-oidc-secret
      namespace: prometheus
