---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-bucket-oidc-secret
  namespace: prometheus
spec:
  encryptedData:
    client-secret: AgA4jSnawIfYQHwTL8Gu3nMDU5BKcZbHpJwCOm3FFriq02lQx6IY9Mi+cxdIcEPe4BHqDGC9j71jDrMN9tZ4q/n6LkSCyZkPULeNtrL3Kj+XSFmHIykFkkZtmbHrcw7478QMdZBBnry/GbUPnpBLRfgdKgd+/khr44hP4Uw4btTqP+vSP0Kl+fDv/DZrQBdjhv0J1sOujGT5qNcJ2Lxgb5naq2zGmc7vSijga5zC2bLHESTHDHO5wqQ4tSsIhOCJPiE86C1nQdN8V1EfyiG/K85xeofw8MlrRWvz8KMWUQZhAy/ZVXi8/MrrjkivwXvjKB5WxjmFo+U2XL4dHsYe07GfikSEP86tveU7PMObNiv7j1l6tpYFWNamP3Q9ZFEP6jlqAqDhduPWfKLeq4iRPM/y8n+oC+8FKy4YR9yys3Z6z3FPqLdTMzRO7PF6CuVoZi32UeTNms8uuMMkarx4XwZfXjyLe1DAXLXgFx/9n3zEW73OXBzpFgk4SyCihFlXsDDhwNG2IVmoM6VTiKpQpY2TFoNbmzfjEX3Etn0p1WjpJudsj/B9nb/YkrtqcLPJsWXLZVc+9KAj8LqI+RMYfg5/aiE8Aeanh/M2FVcYLU0c1o/ClAf6EtrdkQHEUeBTDHqxon/UxMkJMfPBpIICAOnbOmMCMDX552h3SVMiqMKgQLy9sTrJi/w24QQ1tmTRYPDt7Ad78MHYjdcoxUjIe6iDV5fTVfoOy/Tm8rc0HQ2c4PR89G/qxlep/NKI4KjqQsKCsMdatmC4iAeT2uhBDr4QPjE56CcU1VoX+wCG0xVdBVSm/vTzw+KXrdlaAoHscJVCa9oRrdyVEpCGZALf0WkIZiPHKrkhoylzTPsLGVk1EA==
  template:
    metadata:
      name: thanos-bucket-oidc-secret
      namespace: prometheus
