---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-query-oidc-secret
  namespace: prometheus
spec:
  encryptedData:
    client-secret: AgBWQgS/7EYwiV3eYIobtHgs/bFtm9HiuiZ21rAk9AzFUvAsiKYdPWf7XSl1vfpPsEeFoPIwfyXN2aiUhHL8gAQanJlqRfpPD5PMU4L7Is6jw8Ks1i74+L1rA3sDfUn7ZzKCbSomGCjyffv1RZHnW9uTc1MUfhfCAdTg4UtQORNDLIof2BvwPX05EIQ5i71HNKbUE9YN1DBva1KP1asLfxDIBp0hJbXAF20gmXVtW7tY48T+Q5MRwRHRWfYw1qpn7tFbF7j8ji6do9PNbRDIbS+LiHzZPLFSGC0c2qi6KCsaz24fhrFu3yfVlKdFMEcTfwaNJ0xt/qi7VDisInfbBBZlSmR2wDfL+rKxV/0+q43Ou/qlsAtUTFYgpDYeIchuFgL6dGys38/Edjnu4VozCeIx84INaZufJ/K2Q0PpjUvNFWUuzM/D4cTdnM1MLrf52J3Ab0neVoiVNUPZdp+wspDPvNKZTcLM69i9TMxvoTPCcPluEIQoae7FfQwGxuu35tryCG2hJQ6wZCRKFAKXD0IkfW6oEFGioIotDItX5Vf6WqmwqTYA1PW7qfrv9s5GIeC/x9JuUBkVqrdNDcVMJ/lkTrLk9rsH3aBD93SmE/08BWkwJYc3L5uATUeR0Qoyx56zJWxzfT7oJNzHjyYU25SMkHYbTyAdj1WbURZGSwzhdqvdYKlIOXUwWaJh6/ETjYyC72pX7yk2SkIfKttRqNc2yauESRz+zdbugdM5CricZudpAjoqZ9ruqAfwvCtg61dOd35bRglmbuIFAfavlenhftmN0Ydbr33a4LrRTOhIvVP0ceTseofMVnbPLr+7nGh5dPMvU/KwAWodf5hfN9q+h4/c0YyKCQhvqTVIV9sbmA==
  template:
    metadata:
      name: thanos-query-oidc-secret
      namespace: prometheus
