apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistantbase-configuration
  labels:
    home-assistant-config: "1"
data:
  configuration.yaml: |
{{ (.Files.Get "configuration/configuration.yaml") | indent 4 }}
