intel-device-plugins-gpu:
  name: intel-device-plugins-gpu

  sharedDevNum: 1
  logLevel: 2
  enableMonitoring: true
  allocationPolicy: "none"

  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: 'true'

  nodeFeatureRule: true
