---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-oidc-secret
  namespace: prometheus
spec:
  encryptedData:
    client-secret: AgDlV3sIUQ8l1n9hFekm12Q69gpcPtJLOs6XtE76V6XyqWT/SQCBtNdf1KY7qcW86bTifj1EpQPBUwjhQcM6JAJVA0UsBdThf/PSDJBQDdcBnMSRCpRq7al2s0yRYdBrjW3v48Nx6i8rI/4fTIwlDxHFgySwqASpBZUIIoxCgRIOrHTnA2Pbkh3KFkSmsbayX6oNeQfC5sqNgNK+PxNEtm0tS5ec8F8d/eNye6256Q1R3AIQmNmT1/LBd8nVrrT4lKjqi+U0T7PO4tubtvPexpIFQwzbOIaVScjoERA4vGyGdgo5JG+M3YceFt+m4v9PMbE11TZy0XFbrjGoPFains2A3Mxe/EbWa3UwiuZlVutgdBwtRDrtD630f2MwaLljGyul0q4pTAZJ9Hth3Z20clOhKLLQ2/gzHcBIaZD1sFgbwUsqwwIzS12atzuN8oLqiDOmrKX06oJwszbbvSBAwPuMIJ+XMIZ9FHUiTBPaNHHy026XwgEfWVkjgsvkkFi/8H6uTU3jnTkvsSKOLv8u/ZoeVaW1Kwci+yO6I6rfV5ymeBI41rbo7VnrOY4ZgMtry6PsqTuKjF31ghV0C8kMVGXrCSMhP7Z8z8HS8fpN1WojguzQOYElQ1CHvp/n8w3S3O6kM2RZBixLwidsQXpTo4wHnUKLM+54PVks8NeqdZWiNqxpSEPWLI/dJMqKeMDa+NddYLcMl3MkHH0c0qxpUL30AQlFwB0swxEO/VjVbQQMm5R9gSPlEMDj9H9OMN1/AQW0kahMkss/XwqcgO2o1rmdzAAUe4jYAlo2PCX3ZHIaWlLC2g+kzEtPuiD/yKpfp3TwdWIEa8bQdaYxPZVjSUbS5fDF7llePOvJwMXdGHy0IQ==
  template:
    metadata:
      name: prometheus-oidc-secret
      namespace: prometheus
