image:
  repository: ghcr.io/linuxserver/bazarr
  tag: 1.5.2

metrics:
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0

route:
  enabled: true
  hostnames:
    - bazarr.mobrockers.com
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: web-https
