ingress-nginx:
  revisionHistoryLimit: 0

  controller:
    replicaCount: 2
    minReadySeconds: 1 # default is 0 but argocd doesn't like that

    service:
      enabled: true
      external:
        enabled: false 
      internal:
        enabled: true
        externalTrafficPolicy: Local
        annotations: 
          'io.cilium/lb-ipam-ips': 10.0.103.20
        externalIPs:
        - 87.212.115.7

    allowSnippetAnnotations: true
    ingressClassResource:
      default: true
    
    extraArgs:
      default-ssl-certificate: ingress-nginx/default-wildcard-certificate
      update-status-on-shutdown: 'false'
    config:
      enable-ocsp: 'true'
      annotations-risk-level: 'Critical'
      #strict-validate-path-type: 'false'

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
          app.kubernetes.io/instance: '{{ .Release.Name }}'
          app.kubernetes.io/component: controller
      matchLabelKeys:
      - pod-template-hash
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
          app.kubernetes.io/instance: '{{ .Release.Name }}'
          app.kubernetes.io/component: controller
      matchLabelKeys:
      - pod-template-hash
