apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
data:
  configuration.yaml: |
    devices: devices.yaml
    groups: groups.yaml
    availability: 
      enabled: true
    homeassistant:
      enabled: true
      experimental_event_entities: true
    frontend: {{ .Values.frontend | toYaml | nindent 6 }}
    mqtt: {{ .Values.mqtt | toYaml | nindent 6 }}
    serial: 
      port: {{ .Values.zigbee.adapter }}
      adapter: zstack
    advanced:
      pan_id: {{ .Values.zigbee.pan_id }}
      ext_pan_id: {{ .Values.zigbee.ext_pan_id }}
      network_key: '!secret.yaml network_key'
