image:
  repository: ghcr.io/linuxserver/sonarr
  tag: 4.0.16

metrics:
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0

route:
  enabled: true
  hostnames:
    - sonarr.mobrockers.com
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: web-https
