mealie:
  ingress:
    enabled: false

  route:
    enabled: true
    hostnames:
      - mealie.feddema.dev
    parentRefs:
      - name: envoy-gateway
        namespace: envoy-gateway
        sectionName: web-https

  config:
    baseUrl: mealie.feddema.dev
    allowSignups: false
    allowPasswordLogin: false
    oidc:
      enabled: true
      configurationUrl: https://authentik.feddema.dev/application/o/mealie/.well-known/openid-configuration
      clientId: PN9nh2X3931XH3BlVftMzBgECN3jheULqy5hP2E9
      clientSecretName: mealie-oidc-secret
      providerName: Authentik
      adminGroup: 'Admins'
