trivy-operator:
  operator:
    builtInTrivyServer: true
    clusterSbomCacheEnabled: true

    rbacAssessmentScannerEnabled: true
    infraAssessmentScannerEnabled: true
    clusterComplianceEnabled: true
    exposedSecretScannerEnabled: true

    configAuditScannerEnabled: false # We use Kyverno for this purpose

  serviceMonitor:
    enabled: true

trivy-operator-polr-adapter:
  openreports:
    enabled: true
  adapters:
    vulnerabilityReports:
      enabled: true
    clusterVulnerabilityReports:
      enabled: true
    configAuditReports:
      enabled: true
    rbacAssessmentReports:
      enabled: true
    exposedSecretReports:
      enabled: true
    complianceReports:
      enabled: true
    infraAssessmentReports:
      enabled: true
    clusterInfraAssessmentReports:
      enabled: true
