apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloakx-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  source:
    repoURL: https://github.com/florisfeddema/cloud-gitops.git
    targetRevision: HEAD
    path: base/keycloakx

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloakx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
