apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgALpHRoQumttO9SuH8QYaY1hBkNua3LNM2GG5LHphSa3iMImJ/0pNfmi62+hUnnIpBtv+ZjAKbUb7Sde5apxH3OyOhKpS5HFb+8yaETltA4qrDCleSv6Y0qB+ouIRl/LABqj408zb8n5eSHmTU75pBnGOwcbhhUz4IU8NRu2tqsYQ1nZPUEQcOkAlMDInmNgD7TSXQtVdZrW+d7Gw8oTJhUHnsnZZW9yS1F8cWHtzmEOEnwx14Y0O9TxQh6zy4LCeqSbBIYVXCgzRDrn0BmTQOtIW3/bP3xj/0n9VXJk+LJpsYOTYNAP7Agb8P6G/hxL1AcVqpV1S5lQzITJmICnFMo8Rd5n94W6dYG9i6oAVoqdAbaChAaifE7JdKeslitZT+8mD+3uZCp9Zb9EyfUsS9ksKcYsmh1CcYeYNRXctLPkH3L2dVT5edjo+xPf+DCu+Aokb5/1a/p4xCFt/5qPYArxy2HDalD61W4WMW/cn/7Ov8caf2+BHJKGzAfrjuZfPARIFxADFooeLooKj50IT/IU4dJub3YPiOrED3G3hoJUmFtYjL5m07D+rFUXCROKJvcozxx2t/0aBBzprpmJdwKelg9suPIGC3FvvCGFlWPtIrRCXEmYnsYLSKhN69uH9bTwQzwEU/JQufKWgtxe1odLSTF/h2wOnaj9V3vLmWrWbPo+7EcpZY4Xy0dS3GCNA5hB5eqUySEvwB2R3CA0i09iYfDp9uyClmWtQT1DYZjSg==
    admin-user: AgA7ybsZWAQ7R05iqtezC17VCMSDonlaUEHGGTGYHmT6hJvO8Ej9XkJ2Vwy0VjBBVEBGcjIK4YmRXm4AZy8zcMN5PPle+8Pm4ziqhEde/G9Ucv6bPkIniKLnyK88Gs8u37etrzdVVqYvfURRohzVubCot3MRtOSwCeyZGm7kSQaSB3v08y4v1ZOSSAtHRXG5NqbZmT508Q3vqugjQmcuKY+VSQ2tZr8iRBXyAexbDz+k46sCRqdsN5Rg+2eyna9AdKeGVx4Bk4vdrJHP/Up7lveXY0XC2HlgT+8JHmXipi3BFDDA1shniTK6Vf4Ec2MwM/NqiAy7L1GJ8MzxmMjLMol0UX+JN8IkUJ0pwzjuriCip6GvZ++xtQ1ZegqtPQI31S7lBac0yJG2U8xOhWOIaHaUhvnow2KxxbsjH7JqdgsSnP5pDVQtjSkvkt2hlGhuH+HFztiD43gtLeVWQ9Q3xqyfmurwn2pgyPYiRV82oS8MXioFgxsVWA3dmKrjiCHeK0QEuU0gdnNrJV+jWoLXs1gfmfkKfZhT2l8OIC7rbMTIQaNsu7gLjz1910jAsI3OzK/aNroPbpfWBczbtuDoFfh8Pt/0fogntdY9X3aLcHvclaiyb2CwWly8IT8UE7Ny5t1Cw209NN2GdC7VvJ6mverf2tHrfLizofhYQhDmjNkRrZdCA7yqO6BzBVkQ+sRPqiUJnQEylg==
  template:
    metadata:
      name: grafana-credentials
      namespace: grafana
    type: Opaque

