image:
  repository: ghcr.io/linuxserver/radarr
  tag: 5.28.0

metrics:
  image:
    repository: ghcr.io/onedr0p/exportarr
    tag: v2.3.0

route:
  enabled: true
  hostnames:
  - radarr.mobrockers.com
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway
    sectionName: web-https
