apiVersion: v2
name: prometheus
version: 1.1.281

dependencies:
  - name: kube-prometheus-stack
    version: 82.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: thanos
    version: 17.3.1
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
