records:
- name: vpn
  ip: 87.212.115.7
- name: k8s
  ip: 10.0.102.10

routes:
- name: robin
  clientID: 9XuNncO5i9nKVPbjpgjiadXFoEMLUOKyvJXLELj9
  clientSecretSealed: AgDHO21uxHG41WvZY5oaN7Z2rHgsetWYSvoBB8JpOseBcDFE0lNFRYDZoMf69aJDdtFLTvcWRjlC5QiKP9dEB8QzpbPLOG27rmWc8m+hIw2hizm8soX1q9LxLX4uvz4/Bk8v1aiBR+awaU0gTXbybZcenyfZNnJNjiWCM35IH1ypnsQJKkmZnGA4bb3dQJwngz7NpmuJK/yovWXSjy0B+3O7pF05Y4U2ITttqOnmy9FPjO77uR/pblwes8Hp0+ZZ9gKEUat8fXpxMiwLaP1hKOCUFCkxDCAM0khOUAwIbQNl9zJFnbCX3F6POPpVtLf00KN7jyK9/woT40QmcdQiQuuASFVEOZz4SvojKh5MyAKb9Dezdx6T1WMPc4OnR/uAWEpqrSQcsvAavoH97gVYCnEHOYyLAKnABktJwmu/EpAh5dhn2vZsbKfrYwE17QNnZmxRsM2EASXMjhQGzbp2t7E0T2fII8Cb8l9+7BIXaSZePjweNVyCxGWMN5oJhAzZblupIAnRA2qzaCXVio+rrZFpDb//pD/jTW4UKw/ZUmU23/z0IvO4R5fQosuiYiblRpuESHDxkArULKbe8eSvJnbxbmE4YqNjU1cefzbHaPCwLpGaFb/XXUS8XQAsuGA+knBBoEStuAVpWUOC3Fy9PYcXLsZs5Kc8mZvyzrW2DjDAqgtlIHKga0+dyAe6lHUz99vvo54d0enS089BX9ZoH7iv5+Ah9OQGeqYK0+4Jxv4HalkQkk66usroXIttTCLK6iWYZKotmEt42s6xxL/53NyLkVBafd/Zq7WwDlYF1Kb/2SpBIkR94IJezch9hmdRC3aDbiBbCgDpA5QC1etCo5u/gvvtJnTiQjob2/h40wlgVA==
  ip: 10.0.30.45
  port: 80
