records:
- name: vpn
  ip: 87.212.115.7
- name: embla
  ip: 10.0.100.51
- name: embla-1
  ip: 10.0.100.51
- name: embla-2
  ip: 10.0.100.52
- name: embla-3
  ip: 10.0.100.53
- name: embla-4
  ip: 10.0.100.54
- name: embla-5
  ip: 10.0.100.55
- name: k8s
  ip: 10.0.102.10

ingress:
- name: robin
  auth: true
  ip: 10.0.30.45
