gatus-monitor:
  appName: opentherm-monitor
  publicEndpoints:
    - name: opentherm-monitor
  privateEndpoints:
    - name: opentherm-monitor

opentherm-monitor:
  route:
    enabled: true
    hostnames:
      - opentherm-monitor.feddema.dev
    parentRefs:
      - name: envoy-gateway
        namespace: envoy-gateway
        sectionName: web-https
