gatus-monitor:
  appName: opentherm-gateway
  publicEndpoints:
    - name: opentherm-gateway
  privateEndpoints:
    - name: opentherm-gateway

route:
  enabled: true
  hostnames:
    - opentherm-gateway.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
