apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matter-hub
spec:
  rules:
  - host: matter-hub.mobrockers.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: matter-hub
            port:
              name: http
  tls:
  - hosts:
    - matter-hub.mobrockers.com
