apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "adguard.fullname" . }}-sync-config
data:
  LOG_LEVEL: "{{ .Values.sync.config.logLevel }}"
  CRON: "{{ .Values.sync.config.cron }}"
  RUN_ON_START: "true"
  API_PORT: "0"

  ORIGIN_URL: "http://{{ template "adguard.fullname" . }}-web.{{ $.Release.Namespace }}.svc:3000"
  ORIGIN_USERNAME: "admin"
  {{ with .Values.sync.password }}
  ORIGIN_PASSWORD: {{ . }}
  {{ end }}

  {{ range $i, $v := untilStep 1 ((add1 .Values.secondary.replicas) | int ) 1 }}
  REPLICA{{ $v }}_URL: "http://{{ template "adguard.fullname" $ }}-secondary-{{ $i }}.{{ template "adguard.fullname" $ }}-secondary.{{ $.Release.Namespace }}.svc:3000"
  REPLICA{{ $v }}_USERNAME: "admin"
  {{ with $.Values.sync.password }}
  REPLICA{{ $v }}_PASSWORD: {{ . }}
  {{ end }}
  REPLICA{{ $v }}_AUTO_SETUP: "true"
  REPLICA{{ $v }}_DHCP_SERVER_ENABLED: "false"
  {{ end }}
