democratic-csi:

  node:
    # talos config
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""
    # talos config
      # logLevel: debug

  csiDriver:
    name: "org.democratic-csi.iscsi.hdd"

  storageClasses:
  - name: truenas-iscsi-hdd-delete
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"
  - name: truenas-iscsi-hdd-retain
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"
  volumeSnapshotClasses:
  - name: truenas-iscsi-hdd
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
    parameters:
      detachedSnapshots: "true"
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
    # secrets:
    #   node-stage-secret:
    #     node-db.node.session.auth.authmethod: CHAP
    #     node-db.node.session.auth.username: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME}
    #     node-db.node.session.auth.password: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD}
    #     node-db.node.session.auth.username_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN}
    #     node-db.node.session.auth.password_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN}

  driver:
    existingConfigSecret: truenas-iscsi-hdd-config
    config:
      driver: freenas-api-iscsi # required

driverConfigFileSealed: 
  value: AgB+rDkYu42Ved3pqJFX4qsou537vSSp1zdYKS8pKCT1bq+hHGpFEfThjvpsrpgmO4CEvr7/0I223ppP4DfXAouYDeQCkA/YCvnYoTkUnJ0ut1RxQiU+FcNelC1K5xi8n5Z7LIS5UCWw1gRmtrTAoOMRh7Hm7p3VL/LipP3F/2gStZb0ep2Fy2b4rEmHG79XmkRLtaIo0/muoJyeNXuxmb7IlXtP+vyuvSpr9G1ZjUYf1palKflMd5KmF5Lvt/mWrzX3jGCWXulEClVk9MumA1w8NGJIKsUpkMmECwv3D6ZgRXuywFsUFWVP5H73rPoipR/giN4h/uqvZpsEJOyeUaQX3i8oLI2ON933RYbAzu3vfI11h/L0kH/OoLJOE+h0VvdsYi0HXwlk4lp3dtsOSRgGnF9O3puxUNh0HIkGnmmfxtVNI2sK+CnzsV4HDzOpIVP6cwmdtj7+1MwYnl3xoF/ImcqaAQuCL0kKyokGtOIJikytuy/iMKngHU20ZCgTMaoKVHy15PZLe2JvcTEpSGwKV2lOelnsx5hqofhDAsjOC37EE89r8/nz43y6a5RGo0enTi+ZjsL+t9ngr4/EWxZbd5E8niWJlbBGgvYKquaPf7R8Kj2+9Ut9sSjWZEHRnqamaX/Thgy5W24CVafPELxa0+UsyBK0R9c/voz4IvbZPuvwWKOBL7K5ab5/hImbHt1AzYGydPLA/83JnwiQwBP8VKr1jhClgzMwuYjG2GA55RyLDsxM0W/rNXSc4pgz/JaQPJbOUGY+Z0E1ny8WQVvMb76CirkOJP6fzj8lcpxVYjJcuH3/u0h8GVmKrDTxg0lvTC4xM+P+jxZZDXaEaDNqsZkcRF2IWY6P0yDNVfNr9vB0MRUW0BggMEQetEvco8EWXrxSaPrFPg7geelrriYSbUpgfxJjKoKBqa25CYQZFTflssXIEFhPp4jHfaEtgXdltAqIp8wu27qpY5Dnp8BZ33XpWaD0uLehPl6Nv59MLA/W6Xr/s0PtEubED6ncJFPAakUrjVKk+bLsFgWwe50winphqCe3AlFecBHtPCErc+iYUJTVi8h+yVjQZUHvv+Mgg3JLH8MFF4c4a8WbmwuuDN59MuCNqokWCy2XYCZdtYPzC5fi3v4oNj96V+56Cy+/V2fLowZvannK9fvOj6eYyuhjl4Wxs+6AwE/j6+kkYMCu/7/druyu4+ZtCkJH/gGB5vnOf9AFOZ2AoAMYh1WcdI+CsKBvC/B2ypppwm8sCWSYSw3NsOpswF/tPeX3igkGPOl6HrLfRFV4+WWf3h33jK6jF6zP86YJqqmglv61/xqF+SPiGz6+HCLk2jpdCZd7TK3rLawKLPs5H9Ggywc+MSqXORmgkA+vuwzikCH5/UsKbOnXlU4dJ6JMXcX/aLAHPGKqJ8uun+rDftlTOqDMSAYN862qlP0HymKJ1rF4Z57uDQ54ba5EOiGAR/UNKd4V7dLnXhspoXGXhLZx03+KhEK7Y+MeMf59mrTmlShXQXiWjtGLOuFKaum1ZVdq9tY1a4GT8bnJyVMflXoXlt3vhYnlMKda6Y++iIWuXrrgjCZoA6nUBGtLu6r+mAiUuLzOAJcEqNuGysxgog2/cnmMJ2qFJ+oU7CWWFXe8fZnydLDYcnzIS+GYEkOQJAAxDyOuotbNDFm6fcyFqBvWGpeCuHfzrHCSQaXIKOlUf0fPKJvw4aCk0gadLJtucV1vmcW+jeFxY50tQlne9OzhWsOaL8HodoRWfeH1EdSOn5uGmFOwv0RPLxYBzWhVPOiXd3WNUrvNHslCzYs8+BanAMfTVZ5K4o2PlqtqNFu/kMmUL+IHx4FoDJLzj+ww2YUqMGvPNdSuT4rXpO5MUEliE0K8M+qEAYXCQ1UwrVX2l3ArC9W/AzX0tTEK7PrR3wmp8z9E/edPoo6nvZcNNVWTUur2q52zuMddj+Sx8fk9VsxQ1c6uSeJcDGumW6HZoYXIwwM5XoxNDlxnLuihai2HAfdSou+qN9/2BvW/IELIr7Ya5FiItSf73aK/KLZ5ZzvSXBtimMfjQ1gEylcFKcsOt/Pqe8v3Dk2/VtDTGYiQlIOkW/PrGRmgqUDG3njYR39inNA8Jo/7rbaxEaZ7uKNgcG606+MsG6btTylbrd74okIbgR6Wsl6h2u1EtCVfvMe2jAj+ADC4e8Fc13LEOdsGQ/5gmoPHvnK0iVNPq5pg+NGbJ8fhTPdxqiTweqpoQ/nfSaEc+u9nu8cd2yP5hra7RnkXr5LxSqSp10/EGaorGms+d6lavcZs4geoAKpNgRxbEzRyT4YC9SNzy/NgN19Enfv6BagvJtZm3lzIw9d4lWA9+w8/tLNcwqbXS5P3wUwNuxYDjlQyKkTI480sdAykpEApAlwuTUeOxy3Rv+p/oF0zfdsCV3uV2TTcg5fdn2ifbKQ6qq15ocYthJuYps770JvIDYl2cxc96JETgXUIIUWaR5jRaQNSUWz7EHsKzMdGIdqQUMcFMbzm+Lc+q6iG9sFYJ5qZMp415OrlKxVfVDBIpftZrxPjh2tA2SKp4+G5kmukUG71nw/FeF40G/qXHWRKOigIMUWPPq7+axzhOwylHkxoyN1pCjvU/25h+E4G+rx4MSlFTYkfhvwuG7SaIVJnZ9F2r4RQ4xiheotSuDGgE9VnaZm/rF8gj2sigcAvpYgkqNcjjWq7Sky8kkyDj7xmlt2dX3h5EjOSEupKH2LbSAW8AJ6eR9L20yhxInyTSvn5CeDyS42p5S2ZC0VUISzfgoQI3FYDak5R1Sx2XQBpPTroCoRYfXtQ5OyeS45PIIA5rim3QrwDX0dhCiylp8FvweXR7c4pCUSPD69jOijuIP9kLirmjNHD2mnU20HtpXopMV6uexxFqHIwNY8NY0Md7pVmwpEKkJWMvp9oTcMsL/2P3EIGLIyjHsGTrGD0SxjY/m+g7G4MngJRFdlILxK+YltBL/RWvtzkAH0Nxt1JsDjuhu5vB7cIFouyH7WGlJBxaHlfVoet6pQ+k4eB8Ov/zoAS6S/6qqIX/wxU+VlIyBC3HlSdtLcJv7akBTBZ
